version: 1.0.{build}

#fake update

before_build:
- ps: nuget restore

build:
  publish_wap: true
  verbosity: minimal

before_deploy:
# make it explicitely "False" if not scheudled. It is NULL in this case by default
- ps: $env:APPVEYOR_SCHEDULED_BUILD = if ($env:APPVEYOR_SCHEDULED_BUILD -eq "True") {"True"} else {"False"} 

deploy:
- provider: Environment
  name: IIS2
  APPVEYOR_SCHEDULED_BUILD: $(APPVEYOR_SCHEDULED_BUILD)
# test change 2
