version: 1.0.{build}
image: Visual Studio 2015
environment:
  AWSAccessKeyId: AKIAIODIUCY3ETD6M5VQ
  AWSSecretKey:
    secure: LEvzbXpiLkWVvswonFHnAYV9ZS6fEFL3wswjTcIQ6ZXC5j1nynd6N0Bs/VFS8Pa4
before_build:
- ps: nuget restore
build:
  publish_wap_xcopy: true
  verbosity: minimal
deploy_script:

- ps: $artifacts.values | foreach-object {$_.path}

- ps: $packageweb = $artifacts.values | Where-Object { $_.path -like '*WebApplication1.zip' }
- ps: $exe = "C:\Program Files (x86)\AWS Tools\Deployment Tool\awsdeploy.exe"

#- ps: &$exe -w "-DDeploymentPackage=$($packageweb.path)" "-DEnvironment.Name=MyAppWeb-test123" "-DApplication.Name=MyAppWeb123" "-DRegion=eu-west-1" "-DAWSAccessKey=$env:AWSAccessKeyId" "-DAWSSecretKey=$env:AWSSecretKey" "C:\projects\WebApplication1\awsdeploy.txt"
